name: Mirror marketing to GCS (Git = source of truth)

on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths:
      - ".github/workflows/upload-sql-to-gcs.yml"
      - "**"

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions: { contents: read }

    env:
      PROJECT_ID: quick-platform-466015-d5
      GCS_BUCKET: gs://test-git-actions
      REPO_NAME: marketing   # gs://bucket/dags/marketing/<subrepo>/**

    steps:
      - uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: gsutil

      - name: Quick repo view (debug)
        run: |
          echo "Repo top-level:"
          find . -maxdepth 2 -type d -printf "%P\n" | sed 's#^$#.#/' | sort

      - name: Mirror to GCS (delete extras)
        shell: bash
        run: |
          set -Eeuo pipefail
          set -x
          trap 'echo "::error::Failed at line $LINENO: $BASH_COMMAND"' ERR
          shopt -s nullglob

          BUCKET="${GCS_BUCKET%/}"
          DAGS_ROOT="${BUCKET}/dags/${REPO_NAME}"
          DATA_ROOT="${BUCKET}/data"
          CONFIG_ROOT="${BUCKET}/config"

          echo "Bucket root: ${BUCKET}"
          base="${BUCKET#gs://}"; base="gs://${base%%/*}"
          if ! gsutil ls -b "${base}" >/dev/null 2>&1; then
            echo "::warning::Cannot stat bucket ${base} (missing or no permission). Continuing..."
          fi

          # Ensure mandatory top-level dirs exist
          echo | gsutil cp - "${BUCKET}/dags/.gcskeep" >/dev/null 2>&1 || true
          echo | gsutil cp - "${BUCKET}/data/.gcskeep" >/dev/null 2>&1 || true

          # Root hygiene: keep ONLY dags/, data/, config/
          while IFS= read -r top; do
            [[ -z "$top" ]] && continue
            base_name="${top%/}"; base_name="${base_name##*/}"
            if [[ "$base_name" != "dags" && "$base_name" != "data" && "$base_name" != "config" ]]; then
              gsutil -m rm -r "$top" || true
            fi
          done < <(gsutil ls -d "${BUCKET}/*" 2>/dev/null || true)
          gsutil -m rm -r "${BUCKET}/marketing" 2>/dev/null || true
          gsutil -m rm -r "${BUCKET}/Marketing" 2>/dev/null || true

          # Optional repo-level config/
          if [[ -d "config" ]]; then
            gsutil -m rsync -d -r "config" "${CONFIG_ROOT}"
          else
            gsutil -m rm -r "${CONFIG_ROOT}" 2>/dev/null || true
          fi

          # Discover subrepos at repo root (skip dot/infra)
          subrepos=()
          for d in */ ; do
            [[ -d "$d" ]] || continue
            b="${d%/}"
            [[ "$b" == .git || "$b" == .github || "$b" == config || "$b" == .* ]] && continue
            subrepos+=( "$b" )
          done
          echo "Found subrepos: ${subrepos[*]:-<none>}"
          [[ ${#subrepos[@]} -gt 0 ]] || { echo "Nothing to sync."; exit 0; }

          # 1) Mirror DAGs: <sub>/dags/** -> gs://.../dags/${REPO_NAME}/<sub>/**
          for sub in "${subrepos[@]}"; do
            src="$sub/dags"
            dst="${DAGS_ROOT}/${sub}"
            if [[ -d "$src" ]]; then
              gsutil -m rsync -d -r "$src" "$dst"
            else
              gsutil -m rm -r "$dst" 2>/dev/null || true
            fi
          done
          # Prune stale DAG subrepos
          while IFS= read -r gcs_path; do
            [[ -z "$gcs_path" ]] && continue
            gsub="${gcs_path%/}"; gsub="${gsub##*/}"
            keep=false; for sub in "${subrepos[@]}"; do [[ "$sub" == "$gsub" ]] && keep=true && break; done
            if [[ "$keep" == false ]]; then gsutil -m rm -r "$gcs_path" || true; fi
          done < <(gsutil ls -d "${DAGS_ROOT}/*" 2>/dev/null || true)

          # 2) Mirror all NON-dags content with a single rsync per subrepo (deep delete)
          #    This deletes any extra folder at ANY depth under data/<subrepo>/.
          for sub in "${subrepos[@]}"; do
            gsutil -m rsync -d -r -x '(^|/)dags(/|$)' "$sub" "${DATA_ROOT}/${sub}/"
          done
          # Prune stale DATA subrepos not in Git
          while IFS= read -r gpath; do
            [[ -z "$gpath" ]] && continue
            gsub="${gpath%/}"; gsub="${gsub##*/}"
            keep=false; for sub in "${subrepos[@]}"; do [[ "$sub" == "$gsub" ]] && keep=true && break; done
            if [[ "$keep" == false ]]; then gsutil -m rm -r "$gpath" || true; fi
          done < <(gsutil ls -d "${DATA_ROOT}/*" 2>/dev/null || true)

          set +x
          echo "Final listing:"
          gsutil ls -r "${BUCKET}/dags/"   || true
          gsutil ls -r "${BUCKET}/data/"   || true
          gsutil ls -r "${BUCKET}/config/" || true
          echo "✅ Mirror complete."
