name: Upload SQL to GCS

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: quick-platform-466015-d5

      - name: Upload SQL file to GCS
        run: |
          SQL_FILE=$(find . -name "*.sql" | head -n 1)

          if [ -z "$SQL_FILE" ]; then
            echo "❌ No SQL file found!"
            exit 1
          fi

          echo "✅ Found SQL file: $SQL_FILE"

          gsutil cp "$SQL_FILE" "gs://test-git-actions/$(basename $SQL_FILE)"
