name: Mirror marketing to GCS (hard delete + exact mirror)

on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths:
      - ".github/workflows/upload-sql-to-gcs.yml"
      - "**"

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions: { contents: read }

    env:
      PROJECT_ID: quick-platform-466015-d5
      GCS_BUCKET: gs://test-git-actions
      REPO_NAME: marketing   # used under dags/: gs://bucket/dags/marketing/<subrepo>

    steps:
      - uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: gsutil

      - name: Mirror (hard delete first, then copy)
        shell: bash
        run: |
          set -Eeuo pipefail
          set -x
          trap 'echo "::error::Failed at line $LINENO: $BASH_COMMAND"' ERR
          shopt -s nullglob

          BUCKET="${GCS_BUCKET%/}"
          DAGS_ROOT="${BUCKET}/dags/${REPO_NAME}"
          DATA_ROOT="${BUCKET}/data"
          CONFIG_ROOT="${BUCKET}/config"

          # Detect where subrepos live: repo root or marketing/
          FS_ROOT="."
          if [[ -d "marketing" ]] && find "marketing" -mindepth 1 -maxdepth 1 -type d -print -quit | grep -q .; then
            FS_ROOT="marketing"
          fi
          echo "FS_ROOT=${FS_ROOT}"

          # Ensure mandatory top-level dirs exist
          echo | gsutil cp - "${BUCKET}/dags/.gcskeep" >/dev/null 2>&1 || true
          echo | gsutil cp - "${BUCKET}/data/.gcskeep" >/dev/null 2>&1 || true

          # Root hygiene: keep ONLY dags/, data/, config/
          while IFS= read -r top; do
            [[ -z "$top" ]] && continue
            base="${top%/}"; base="${base##*/}"
            if [[ "$base" != "dags" && "$base" != "data" && "$base" != "config" ]]; then
              gsutil -m rm -r "$top" || true
            fi
          done < <(gsutil ls -d "${BUCKET}/*" 2>/dev/null || true)

          # Optional repo-level config/
          if [[ -d "config" ]]; then
            gsutil -m rsync -d -r "config" "${CONFIG_ROOT}"
          else
            gsutil -m rm -r "${CONFIG_ROOT}" 2>/dev/null || true
          fi

          # Gather subrepos under FS_ROOT
          mapfile -t subrepos < <(find "$FS_ROOT" -mindepth 1 -maxdepth 1 -type d -printf "%f\n" | grep -vE '^(\.git|\.github|config|\.)$' | sort)
          echo "Subrepos: ${subrepos[*]:-<none>}"
          [[ ${#subrepos[@]} -gt 0 ]] || { echo "Nothing to sync."; exit 0; }

          # Helper for FS_ROOT-relative paths
          src_path() { echo "${FS_ROOT%/}/$1"; }

          # ========== DAGS: hard delete then copy ==========
          for sub in "${subrepos[@]}"; do
            src="$(src_path "$sub")/dags"
            dst="${DAGS_ROOT}/${sub}"
            # wipe destination completely first
            gsutil -m rm -r "${dst}" 2>/dev/null || true
            if [[ -d "$src" ]]; then
              echo "Copy DAGs: $src -> $dst"
              gsutil -m rsync -r "$src" "$dst"
            else
              echo "No DAGs for $sub (left deleted)."
            fi
          done
          # prune any stale DAG subrepos (if top-level folder somehow exists)
          while IFS= read -r g; do
            [[ -z "$g" ]] && continue
            base="${g%/}"; base="${base##*/}"
            keep=false; for s in "${subrepos[@]}"; do [[ "$s" == "$base" ]] && keep=true && break; done
            if [[ "$keep" == false ]]; then gsutil -m rm -r "$g" || true; fi
          done < <(gsutil ls -d "${DAGS_ROOT}/*" 2>/dev/null || true)

          # ========== DATA: hard delete then copy everything EXCEPT dags ==========
          for sub in "${subrepos[@]}"; do
            src="$(src_path "$sub")"
            dst="${DATA_ROOT}/${sub}/"
            # wipe destination completely first
            gsutil -m rm -r "${dst}" 2>/dev/null || true
            # copy whole subrepo except its dags/ folder
            echo "Copy DATA (exclude dags): $src -> $dst"
            gsutil -m rsync -r -x '(^|/)dags(/|$)' "$src" "$dst"
          done
          # prune any stale DATA subrepos
          while IFS= read -r g; do
            [[ -z "$g" ]] && continue
            base="${g%/}"; base="${base##*/}"
            keep=false; for s in "${subrepos[@]}"; do [[ "$s" == "$base" ]] && keep=true && break; done
            if [[ "$keep" == false ]]; then gsutil -m rm -r "$g" || true; fi
          done < <(gsutil ls -d "${DATA_ROOT}/*" 2>/dev/null || true)

          # Deep hygiene: ensure nothing under dags/ except dags/marketing/**
          while IFS= read -r uri; do
            [[ -z "$uri" ]] && continue
            [[ "$uri" == "${BUCKET}/dags/.gcskeep" ]] && continue
            case "$uri" in
              "${DAGS_ROOT}/"*) : ;;  # allowed
              *) gsutil -m rm -r "$uri" || true ;;
            esac
          done < <(gsutil ls -r "${BUCKET}/dags/**" 2>/dev/null || true)

          set +x
          echo "Final listing:"
          gsutil ls -r "${BUCKET}/dags/"   || true
          gsutil ls -r "${BUCKET}/data/"   || true
          gsutil ls -r "${BUCKET}/config/" || true
          echo "✅ Hard mirror complete."
