name: Mirror marketing to GCS (hard delete + exact mirror)

on:
  workflow_dispatch:
  push:
    branches: ["**"]
    paths:
      - ".github/workflows/upload-sql-to-gcs.yml"
      - "**"

jobs:
  sync:
    runs-on: ubuntu-latest
    permissions: { contents: read }

    env:
      PROJECT_ID: quick-platform-466015-d5
      GCS_BUCKET: gs://test-git-actions
      REPO_NAME: marketing   # DAGS -> gs://bucket/dags/marketing/<subrepo>; DATA -> gs://bucket/data/marketing/<subrepo>

    steps:
      - uses: actions/checkout@v4

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Setup gcloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}
          install_components: gsutil

      - name: Mirror (hard delete first, then copy)
        shell: bash
        run: |
          set -Eeuo pipefail
          set -x
          trap 'echo "::error::Failed at line $LINENO: $BASH_COMMAND"' ERR
          shopt -s nullglob

          BUCKET="${GCS_BUCKET%/}"
          DAGS_ROOT="${BUCKET}/dags/${REPO_NAME}"
          DATA_ROOT="${BUCKET}/data/${REPO_NAME}"   # <<<<<< changed
          CONFIG_ROOT="${BUCKET}/config"

          # Detect where subrepos live: repo root or marketing/
          FS_ROOT="."
          if [[ -d "marketing" ]] && find "marketing" -mindepth 1 -maxdepth 1 -type d -print -quit | grep -q .; then
            FS_ROOT="marketing"
          fi
          echo "FS_ROOT=${FS_ROOT}"

          # Ensure mandatory top-level dirs exist
          echo | gsutil cp - "${BUCKET}/dags/.gcskee
