# Sync DAGs for every subfolder under marketing/
- name: Sync DAG contents to Composer (mirror)
  run: |
    set -euo pipefail
    shopt -s nullglob

    BUCKET="gs://quick-platform-466015-d5/test-git-actions"   # <-- replace
    REPO_ROOT="marketing"

    # collect subrepos present in Git under marketing/
    subrepos=()
    for d in "$REPO_ROOT"/*; do
      [ -d "$d" ] || continue
      subrepos+=( "$(basename "$d")" )
    done

    echo "Found subrepos: ${subrepos[*]:-<none>}"

    # 1) Sync DAGs for each subrepo (creates path if missing; -d deletes extras)
    for sub in "${subrepos[@]}"; do
      src="$REPO_ROOT/$sub/dags"
      dst="$BUCKET/dags/$REPO_ROOT/$sub/dags"
      if [ -d "$src" ]; then
        echo "Syncing DAGs: $src -> $dst"
        gsutil -m rsync -d -r "$src" "$dst"
      else
        echo "No DAGs in $REPO_ROOT/$sub — removing GCS dags path if present: $BUCKET/dags/$REPO_ROOT/$sub"
        gsutil -m rm -r "$BUCKET/dags/$REPO_ROOT/$sub" || true
      fi
    done

    # 2) Remove any stale subfolders in GCS dags that are not present in Git
    echo "Cleaning up stale GCS dags directories under $BUCKET/dags/$REPO_ROOT ..."
    while IFS= read -r gcs_path; do
      # skip if no results
      [ -n "$gcs_path" ] || continue
	  gcs_sub=$(echo "$gcs_path" | sed 's:/*$::' | awk -F/ '{print $NF}')
      keep=false
      for sub in "${subrepos[@]}"; do
        [ "$sub" = "$gcs_sub" ] && keep=true && break
      done
      if [ "$keep" = false ]; then
        echo "Deleting stale GCS dags path: $gcs_path"
        gsutil -m rm -r "$gcs_path" || true
      fi
    done < <(gsutil ls -d "$BUCKET/dags/$REPO_ROOT/*" 2>/main/null || true)

# Sync data (everything except dags) for every subfolder under marketing/
- name: Sync other marketing folders to data/ (mirror)
  run: |
    set -euo pipefail
    shopt -s nullglob

    BUCKET="gs://bucket_name"   # <-- replace
    REPO_ROOT="marketing"

    # collect subrepos present in Git under marketing/
    subrepos=()
    for d in "$REPO_ROOT"/*; do
      [ -d "$d" ] || continue
      subrepos+=( "$(basename "$d")" )
    done

    # 1) Sync other folders for each subrepo (exclude dags)
    for sub in "${subrepos[@]}"; do
      has_other=false
      for dir in "$REPO_ROOT/$sub"/*; do
        [ -d "$dir" ] || continue
        folder=$(basename "$dir")
        if [ "$folder" != "dags" ]; then
          has_other=true
          dst="$BUCKET/data/$REPO_ROOT/$sub/$folder/"
          echo "Syncing $dir -> $dst"
          gsutil -m rsync -d -r "$dir" "$dst"
        fi
      done
    # 2) Remove any stale subfolders in GCS data that are not present in Git
    echo "Cleaning up stale GCS data directories under $BUCKET/data/$REPO_ROOT ..."
    while IFS= read -r gcs_path; do
      [ -n "$gcs_path" ] || continue
      gcs_sub=$(echo "$gcs_path" | sed 's:/*$::' | awk -F/ '{print $NF}')
      keep=false
      for sub in "${subrepos[@]}"; do
        [ "$sub" = "$gcs_sub" ] && keep=true && break
      done
      if [ "$keep" = false ]; then
        echo "Deleting stale GCS data path: $gcs_path"
        gsutil -m rm -r "$gcs_path" || true
      fi
    done < <(gsutil ls -d "$BUCKET/data/$REPO_ROOT/*" 2>/main/null || true)
